services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=pluma_sphere'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
