spring:
  application:
    name: PlumaSphere-Backend
  jpa:
    hibernate.ddl-auto: update
config:
  jwt:
    iss: your_iss
    expiration:
      access_token: 5
      refresh_token: 15
  cors:
    allowed_origins:
      - http://example.com