spring:
  application:
    name: PlumaSphere-Backend
  jpa:
    hibernate.ddl-auto: update
    open-in-view: false
config:
  jwt:
    iss: your_iss
    expiration:
      access_token: 5
      refresh_token: 0
  cors:
    allowed_origins:
      - http://example.com
  server_full_address: http://example.com:8080
  cache:
    like_sync_interval: 300000
resilience4j:
  ratelimiter:
    instances:
      get-identity:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 10ms
        registerHealthIndicator: true
